import DashboardNav from "@/components/sections/Dashboard/DashboardNav";
import { DecodeAndVerifyJWT } from "@/functions/Decode";
import { Providers } from "@/providers/Providers";
import { Metadata } from "next";
import { Roboto } from "next/font/google";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const roboto = Roboto({
    weight: ["100", "300", "400", "500", "700", "900"],
    subsets: ["latin"],
    variable: "--font-roboto",
});

export default async function DashboardLayout({ children }: { children: React.ReactNode }) {
    const user = await DecodeAndVerifyJWT()

    return (
        <html className="light" lang="en">
            <body className={` antialiased`}>
                <Providers>
                    <DashboardNav user={user} />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
